function Head() {
  return (
    <>
      <title>HipNode</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by HipNode" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

export default Head;
